services:
  - type: web
    name: app
    runtime: docker
    repo: https://github.com/pratikmystery/bitespeed-task.git

  - type: pserv
    name: db
    runtime: image
    image: 
      url: docker.io/mysql:5.7.24
    envVars:
      - key: MYSQL_DATABASE
        value: test
      - key: MYSQL_USER
        value: user
      - key: MYSQL_PASSWORD
        value: secret
      - key: MYSQL_ROOT_PASSWORD
        value: root
